language: android

jdk:
  - oraclejdk11

android:
  components:
    - tools
    - build-tools-33.0.0
    - android-33
    - platform-tools
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

script:
  ./gradlew checkstyle build --s
